### ISSUE TITLE
Tentativa de contato

### ISSUE THREAD

**Issue by JoaozinhoKz4** [TobyMosque/ws-quasar-storybook-designsystem#1]
Olá tudo bem? Primeiramente gostaria de agradecer teu empenho na comunidade de Quasar do Brasil.
Além disso, onde poderia entrar em contato? Estou desenvolvendo uma aplicação e cai num problema que já me tomou uma semana e ainda não consegui solucionar. Poderíamos conversar?

**Comment by TobyMosque** [comment]
era mais fácil perguntar pelo Discord ou até pelo Instagram, mas qual era a duvida?
